### ISSUE TITLE
It fails for "numpy is required during installation" when we trying to install sysidentpy from requirements.txt.

### ISSUE THREAD

**Issue by Yangsh-w** [wilsonrljr/sysidentpy#52] opened 2021-08-05 03:12 UTC
**Describe the bug**
It fails for "numpy is required during installation" when we trying to install sysidentpy from requirements.txt.

**To Reproduce**
1. Create a requirements.txt with the below 3 packages:
`numpy`
`matplotlib  `
`sysidentpy`
2. run pip install command `pip install -r requirements.txt`
3. Issue appears:
![image](https://user-images.githubusercontent.com/76461730/128284151-c744769b-464e-4db0-8a03-c69b5a34d024.png)

**Expected results**
The sysidentpy get installed with all its dependencies.

**Actual results**
sysidentpy failed to install for error message "numpy is required during installation".

**Environment**
sysidentpy-0.1.5.3

**Additional context**
Even if we put the `numpy` before `sysidentpy` in requirements.txt does not help. I think this issue is because all the packages are only downloaded in the first pass and then installed all together at the end. 

**Workaround**
We currently have a workaround to pip install all the dependency packages separately before we install for the requirements.txt. But this requires us to do these in a Linux VM as our target server is Linux OS while we are developing in Windows.
So it would be great if we could have an actual solution for this issue. Thanks in advance!

**Comment by wilsonrljr** [comment] 2021-08-14 21:43
Hi @Yangsh-w, thanks for pointing this out. The fix will be in the next update coming in the next days (with new features and improvments). I will keep this open til there so you can validate the issue is gone. As soon as the update is published I'll let you know!

**Comment by wilsonrljr** [comment] 2021-09-23 01:27
Hi @Yangsh-w. Could you test if the error persists in the new update?

**Comment by wilsonrljr** [comment] 2022-02-02 23:34
I'm closing this issue because the error was fixed in v0.1.7. If you need any help, just let me know.

**Closed by wilsonrljr** 2022-02-02 23:34 UTC
